# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  packages:
    all:
      compiler: [gcc]
      variants: +mpi
      providers:
        mpi: [mpich]
    mpich:
      version:
      - 3.2.1
      variants: ~wrapperrpath
    gcc:
      version: [7.3.0]
  # add package specs to the `specs` list
  #TuckerMPI does not yet have a spack package. +fortrilinos trilinos variant does not yet build
  specs: [ py-libensemble^python@3.7.3, flecsi,magma,slate,hypre,mfem,kokkos,trilinos@12.14.1+dtk+intrepid2+shards,sundials,petsc,strumpack,superlu,tasmanian]
  mirrors: {}
  modules:
    enable: []
  repos: []
  config: {}

