spack:
  packages:
    all:
      compiler: [gcc@7.3.0]
      variants: +mpi
      providers:
        mpi: [mpich]
      buildable: true
      version: []
      paths: {}
      modules: {}
    mpich:
      version: [3.2.1]
      variants: ~wrapperrpath
      buildable: true
      providers: {}
      paths: {}
      modules: {}
      compiler: []
    gcc:
      version: [7.3.0]
      buildable: true
      providers: {}
      paths: {}
      modules: {}
      compiler: []
  specs:
  - py-libensemble^python@3.7.3
  - flecsi
  - magma
  - slate
  - hypre
  - mfem
  - kokkos
  - trilinos@12.14.1+dtk+intrepid2+shards
  - sundials
  - petsc
  - strumpack
  - superlu
  - tasmanian
  view: false
