modules:
  enable:
  - lmod
  lmod:
    core_compilers:
    - '!!CORECOMPILER!!'
    hierarchy:
    - mpi
    hash_length: 4
    whitelist:
    - 'gcc'
    blacklist:
    - '%!!CORECOMPILER!!'
    all:
      environment:
        set:
          '{name}_ROOT': '{prefix}'
  prefix_inspections:
    bin:
    - PATH
    man:
    - MANPATH
    share/man:
    - MANPATH
    share/aclocal:
    - ACLOCAL_PATH
    lib:
    - LIBRARY_PATH
    lib64:
    - LIBRARY_PATH
    include:
    - CPATH
    lib/pkgconfig:
    - PKG_CONFIG_PATH
    lib64/pkgconfig:
    - PKG_CONFIG_PATH
    '':
    - CMAKE_PREFIX_PATH 
  
