packages:
  all:
    target: [!!TARGETARCH!!]
    compiler: [gcc@7.3.0]
    variants: +mpi
    providers:
      mpi: [mpich]
  mpich:
    version: [3.2.1]
    variants: ~wrapperrpath
    buildable: true
  gcc:
    version: [7.3.0]
    variants: +strip
    buildable: true
  patchelf:
    compiler: [!!CORECOMPILER!!]
