alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

sed -i 's/module tcl/module lmod/g' ${SPACK_ROOT}/share/spack/setup-env.sh
source ${SPACK_ROOT}/share/spack/setup-env.sh
source `spack location -i lmod`/lmod/lmod/init/bash
module purge
module unuse /spack/share/spack/modules/linux-rhel7-ppc64le
module use /spack/share/spack/lmod/linux-rhel7-ppc64le/Core
module load gcc
module load mpich
